NiCATPortal/Models/Course.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace NiCATPortal.Models
{
    public class Course
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Morate uneti naziv kursa")]
        [MaxLength(50, ErrorMessage = "Maksimalna dužina naziva je 50 karaktera")]
        [Display(Name = "Naziv kursa")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Morate uneti godinu održavanja kursa")]
        [Display(Name = "Godina")]
        [Range(2014, 2050, ErrorMessage = "Godina kursa mora biti u opsegu od 2014. do 2050.")]
        public int Year { get; set; }

        [Display(Name = "Opis kursa")]
        public string Description { get; set; }

        public virtual ICollection<Teacher> Teachers { get; set; }
        public virtual ICollection<Student> Students { get; set; }

        public virtual ICollection<Evaluation> Evaluations { get; set; }
        public virtual ICollection<Literature> Literatures { get; set; }
        public virtual ICollection<Homework> Homework { get; set; }
    }
}

NiCATPortal/Models/Teacher.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NiCATPortal.Models
{
    public class Teacher : ApplicationUser
    {
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<Literature> Literature { get; set; }
    }
}

NiCATPortal/Controllers/CVsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NiCATPortal.Models;
using System.IO;
using System.Web.UI;

namespace NiCATPortal.Controllers
{
    public class CVsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: CVs
        [Route("CV")]
        public ActionResult Index()
        {
            return View(db.CVs.ToList());
        }

        // GET: CVs/Details/5
        [Route("CV/Detaljnije/{id}")]
        public ActionResult Details(string studentId)
        {
            if (studentId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(studentId);
            if (student.CV == null)
            {
                return RedirectToAction("Create");
            }
            else
            {
                ViewBag.studentId = studentId;
                return View(student.CV);
            }
        }
        [Route("CV/Download/{id}")]
        public ActionResult DownloadCV(int id)
        {
            //UNCOMMENT
            //Student student = (Student)db.CVs.Where(c => c.Id == cvId).Select(c => c.Student);
            //CV cv = db.CVs.First(c => c.Student.Id == student.Id);
            CV cv = db.CVs.Find(id);
            string filename = cv.FileName;
            return File(Server.MapPath("~/Images/") + filename, MimeMapping.GetMimeMapping(filename), filename);
        }

        // GET: CVs/Create
        [Route("CV/Dodaj")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: CVs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("CV/Dodaj")]
        public ActionResult Create(/*[Bind(Include = "Id,FileName")] CV cV*/HttpPostedFileBase fileParameter)
        {
            //if (ModelState.IsValid)
            //{
            //    db.CVs.Add(cV);
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}

            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];
                string sId = Request.Form["studentId"];
                Student student = db.Students.Find(sId);
                if (student.CV != null)
                {
                    CV oldCV = db.CVs.Find(student.CV.Id);
                    db.CVs.Remove(oldCV);
                }
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var newCV = new CV { FileName = fileName };
                    student.CV = newCV;
                    db.CVs.Add(newCV);
                    db.SaveChanges();
                    var path = Path.Combine(Server.MapPath("~/Images/"), fileName);
                    file.SaveAs(path);
                }
            }

            return RedirectToAction("Details", "Students", new { id= Request.Form["studentId"] });
        }

        // GET: CVs/Edit/5
        [Route("CV/Izmeni/{id?}")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CV cV = db.CVs.Find(id);
            if (cV == null)
            {
                return HttpNotFound();
            }
            return View(cV);
        }

        // POST: CVs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("CV/Izmeni")]
        public ActionResult Edit([Bind(Include = "Id,FileName")] CV cV)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cV).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cV);
        }

        // GET: CVs/Delete/5
        [Route("CV/Obrisi/{id?}")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CV cV = db.CVs.Find(id);
            if (cV == null)
            {
                return HttpNotFound();
            }
            return View(cV);
        }

        // POST: CVs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Route("CV/Obrisi/{id?}")]
        public ActionResult DeleteConfirmed(int id)
        {
            CV cV = db.CVs.Find(id);
            db.CVs.Remove(cV);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NiCATPortal/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Linq.Dynamic;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NiCATPortal.Models;
using System.IO;
using System.Data.Entity.Infrastructure;

namespace NiCATPortal.Controllers
{
    [Authorize]
    public class CoursesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        [Route("Kursevi")]
        public ActionResult Index(string sortBy = "Name", string sortOrder = "ASC", int page = 1, int pageSize = 2, string search = "")
        {
            var courses = db.Courses
                            .Where(x => x.Name.Contains(search))
                            .OrderBy(string.Format("{0} {1}", sortBy, sortOrder));
            //then we get total count
            var count = courses.Count();
            //then we page the records
            courses = courses.Skip((page - 1) * pageSize).Take(pageSize);

            var model = new CourseGridViewModel()
            {
                SortOrder = sortOrder,
                SortBy = sortBy,
                Page = page,
                PageSize = pageSize,
                Search = search,
                Courses = courses.ToList(),
                Count = count
            };

            return View(model);
        }
        [Route("Kursevi/Spisak/{id}")]
        public ActionResult UserCourses(string userId)
        {
            if (userId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<Course> courses = new List<Course>();
            var user = db.Users.FirstOrDefault(t => t.Id.Equals(userId));
            if(user is Teacher)
            {
                courses = (user as Teacher).Courses.ToList();
            }
            else
            {
                courses = (user as Student).Courses.ToList();
            }
            ViewBag.userId = userId;
            return View(courses);
        }

        [Route("Kursevi/Lista/{id?}")]
        public ActionResult CourseUsersList(int? id, string usersType)
        {
            if (id == null || usersType == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            ViewBag.CourseName = course.Name;
            if (usersType.Equals("Students"))
            {
                List<Student> res = course.Students.ToList();
                ViewBag.UsersType = "Studenti";
                return View(res);
            }
            else
            {
                List<Teacher> res = course.Teachers.ToList();
                ViewBag.UsersType = "Predavači";
                return View(res);
            }
        }

        //public ActionResult TeachersList(string userId)
        //{
        //    if (userId == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    var courses = (db.Users.FirstOrDefault(t => t.Id.Equals(userId)) as Teacher).Courses.ToList();
        //    return View(courses);
        //}
        [Route("Kursevi/DodajPolaznika/{id?}")]
        public ActionResult AddUserToCourse(int? id, string userId)
        {
            if (userId == null || id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var course = db.Courses.Find(id);
            var user = db.Users.FirstOrDefault(t => t.Id.Equals(userId));
            if(user is Student)
            {
                (user as Student).Courses.Add(course);
            }
            else
            {
                (user as Teacher).Courses.Add(course);
            }
            db.SaveChanges();
            return RedirectToAction("Details", new { id=id, userId=userId});
        }

        [Route("Kursevi/UkloniPolaznika/{id?}")]
        public ActionResult RemoveUserFromCourse(int? id, string userId)
        {
            if (userId == null || id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var course = db.Courses.Find(id);
            var user = db.Users.FirstOrDefault(t => t.Id.Equals(userId));
            if (user is Student)
            {
                (user as Student).Courses.Remove(course);
            }
            else
            {
                (user as Teacher).Courses.Remove(course);
            }
            db.SaveChanges();
            return RedirectToAction("Details", new { id = id, userId = userId });
        }

        // GET: Courses/Details/5
        [Route("Kursevi/Detaljnije/{id?}")]
        public ActionResult Details(int? id, string userId)
        {
            if (id == null || userId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            ApplicationUser user = db.Users.FirstOrDefault(s => s.Id.Equals(userId));
            ViewBag.UserContainsCourse = false;
            if (user is Teacher)
            {
                var query1 = from c in db.Courses
                             where c.Teachers.Any(s => s.Id.Equals(userId))
                             select c;
                if(query1.ToList().ToList().Contains(course))
                    ViewBag.UserContainsCourse = true;
            }
            else if(user is Student)
            {
                var query2 = from c in db.Courses
                             where c.Students.Any(s => s.Id.Equals(userId))
                             select c;
                if (query2.ToList().ToList().Contains(course))
                    ViewBag.UserContainsCourse = true;
            }
             
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        [Route("Kursevi/DodajDomaci/{id?}")]
        public ActionResult UploadHomework(int? courseId)
        {
            if (courseId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(courseId);
            return View(course);
        }

        [HttpPost]
        [Route("Kursevi/DodajDomaci")]
        public ActionResult UploadHomework(HttpPostedFileBase fileParameter)
        {
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];
                int cId = Int32.Parse(Request.Form["courseId"]);
                string uId = Request.Form["userId"];
                Course course = db.Courses.Find(cId);
                //Course updatedCourse = new Course { Id = course.Id, Description = course.Description, Name = course.Name, Year = course.Year };
                //if (course.Literatures == null)
                //{
                //    updatedCourse.Literatures = new List<Literature>();
                //}
                Student usr = db.Students.Find(uId);
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var newHomework = new Homework { FileName = fileName, Course = course, Student = usr };
                    db.Homework.Add(newHomework);
                    //course.Homework.Add(newHomework);
                    db.SaveChanges();
                    var path = Path.Combine(Server.MapPath("~/Files/Homework/"), fileName);
                    file.SaveAs(path);
                }
            }

            return RedirectToAction("Index","Homework",new { courseId = Int32.Parse(Request.Form["courseId"]) });
        }

        [Route("Kursevi/DodajLiteraturu/{id?}")]
        public ActionResult UploadLiterature(int? courseId)
        {
            if (courseId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(courseId);
            return View(course);
        }

        [HttpPost]
        [Route("Kursevi/DodajLiteraturu")]
        public ActionResult UploadLiterature(HttpPostedFileBase fileParameter)
        {
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];
                int cId = Int32.Parse(Request.Form["courseId"]);
                string uId = Request.Form["userId"];
                Course course = db.Courses.Find(cId);
                Course updatedCourse = new Course { Id = course.Id, Description = course.Description, Name = course.Name, Year = course.Year };
                if (course.Literatures == null)
                {
                    updatedCourse.Literatures = new List<Literature>();
                }
                Teacher usr = db.Teachers.Find(uId);
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var newLiterature = new Literature { FileName=fileName, Course=course, Teacher=usr };
                    course.Literatures.Add(newLiterature);
                    db.Literature.Add(newLiterature);
                    db.SaveChanges();
                    var path = Path.Combine(Server.MapPath("~/Files/Literature/"), fileName);
                    file.SaveAs(path);
                }
            }

            return RedirectToAction("Index", "Literature", new { courseId = Int32.Parse(Request.Form["courseId"]), userId = Request.Form["userId"] });
        }

        // GET: Courses/Create
        [Authorize(Order = 1,Roles = Role.ADMIN)]
        [Route("Kursevi/DodajKurs")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create

NiCATPortal/Views/Teachers/Courses.cshtml
@{
    ViewBag.Title = "Kursevi";
}

<h2>Kursevi</h2>

NiCATPortal/Views/Teachers/Create.cshtml
@model NiCATPortal.Models.Teacher

@{
    ViewBag.Title = "Kreiranje novog profesora";
}

<h2>Kreiranje novog profesora</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Novi profesor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("Ime", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Prezime", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.Label("Potvrđen email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.EmailConfirmed)
                    @Html.ValidationMessageFor(model => model.EmailConfirmed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

        <div class="form-group">
            @Html.Label("Lozinka", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.PasswordHash, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PasswordHash, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Broj telefona", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kreiraj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Nazad", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NiCATPortal/Views/Teachers/Delete.cshtml
@model NiCATPortal.Models.Teacher

@{
    ViewBag.Title = "Brisanje";
}

<h2>Brisanje</h2>

<h3>Da li ste sigurni da želite da obrišete korisnika?</h3>
<div>
    <h4>Predavač</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Ime")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayName("Prezime")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayName("Broj telefona")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Obriši" class="btn btn-default" /> |
            @Html.ActionLink("Nazad", "Index")
        </div>
    }
</div>

NiCATPortal/Views/Teachers/Details.cshtml
@model NiCATPortal.Models.Teacher
@using Microsoft.AspNet.Identity;
@{
    ViewBag.Title = "Profil";
}

<h2>Profil</h2>

<div>
    <h4>Predavač</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Ime")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayName("Prezime")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayName("Broj telefona")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayName("Kursevi:")
        </dt>

        <dd>
            @Html.ActionLink("Pregled", "UserCourses", "Courses", new { userId = Model.Id }, null)
        </dd>

        @*<dt>
            @Html.DisplayName("CV")
        </dt>

        <dd>
            @Html.ActionLink("Pregled", "Details", "CVs", new { studentId = User.Identity.GetUserId() }, null)
        </dd>*@

    </dl>
</div>
@if (User.Identity.GetUserId().Equals(Model.Id))
{
    <p>
        @Html.ActionLink("Ažuriraj", "Edit", new { id = Model.Id })<span> | </span>
        @Html.ActionLink("Podešavanja", "Index", "Manage")
    </p>
}
@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Ažuriraj", "Edit", new { id = Model.Id })
    </p>
}

NiCATPortal/Views/Teachers/Edit.cshtml
@model NiCATPortal.Models.Teacher

@{
    ViewBag.Title = "Ažuriranje";
}

<h2>Ažuriranje</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Predavač</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.Label("Ime", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Prezime", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display:none">
            @Html.LabelFor(model => model.EmailConfirmed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.EmailConfirmed)
                    @Html.ValidationMessageFor(model => model.EmailConfirmed, "", new { @class = "text-danger", @type = "hidden" })
                </div>
            </div>
        </div>

        <div class="form-group" style="display:none">
            @Html.LabelFor(model => model.PasswordHash, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PasswordHash, new { htmlAttributes = new { @class = "form-control", @type = "hidden" } })
                @Html.ValidationMessageFor(model => model.PasswordHash, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display:none">
            @Html.LabelFor(model => model.SecurityStamp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecurityStamp, new { htmlAttributes = new { @class = "form-control", @type = "hidden" } })
                @Html.ValidationMessageFor(model => model.SecurityStamp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Broj telefona", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display:none">
            @Html.LabelFor(model => model.PhoneNumberConfirmed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.PhoneNumberConfirmed)
                    @Html.ValidationMessageFor(model => model.PhoneNumberConfirmed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group" style="display:none">
            @Html.LabelFor(model => model.TwoFactorEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TwoFactorEnabled)
                    @Html.ValidationMessageFor(model => model.TwoFactorEnabled, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group" style="display:none">
            @Html.LabelFor(model => model.LockoutEndDateUtc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LockoutEndDateUtc, new { htmlAttributes = new { @class = "form-control", @type = "hidden" } })
                @Html.ValidationMessageFor(model => model.LockoutEndDateUtc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display:none">
            @Html.LabelFor(model => model.LockoutEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.LockoutEnabled)
                    @Html.ValidationMessageFor(model => model.LockoutEnabled, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group" style="display:none">
            @Html.LabelFor(model => model.AccessFailedCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccessFailedCount, new { htmlAttributes = new { @class = "form-control", @type = "hidden" } })
                @Html.ValidationMessageFor(model => model.AccessFailedCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display:none">
            @Html.Label("Korisničko ime", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", @type = "hidden" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sačuvaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@*<div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}